export default TYPES = {
    SIMULATION_PLAYER: {
        SET_DATA: 'SET_DATA',
        SET_CURRENTLY_PLAYED_SECOND: 'SET_CURRENTLY_PLAYED_SECOND',
        SET_SIMULATION_STATUS: 'SET_SIMULATION_STATUS',
        SET_CURRENTLY_PLAYED_FRAME: 'SET_CURRENTLY_PLAYED_FRAME',
        SET_CURRENTLY_PLAYED_FRAMES: 'SET_CURRENTLY_PLAYED_FRAMES'
    }
}